#Skills

skills:
- {name: Communication, value: '8'}
- {name: Organization, value: '7'}
- {name: Learning, value: '10'}
- {name: Version Control, value: '6'}
- {name: Planning, value: '7'}
- {name: Visual Design, value: '7'}
- {name: UX Design, value: '6'}
- {name: Programming, value: '6'}


#Clients

clients:
- {name: 'Maxima', about: "<p><strong>Maxima is one of the biggest supermarket stores in the entire Baltic region.</strong> Maxima Group has 508 stores (as of 2013) in Lithuania, Latvia, Estonia and Bulgaria. Depending on the size of the Maxima stores, they offer 3,000 to 65,000 brands. The group employs more than 29,500 people. Its main headquarters is in Vilnius, Lithuania.</p>", logo: 'clients2.png'}
- {name: 'Salmo', about: "<p><strong>Estonia's biggest fishing equipment producer and distributor.</strong> Salmo makes, distributes, and markets top quality fishing equipment in Estonia. They also have their own fishing school, from which you can get your official fishing licence.</p>", logo: 'clients4.png'}
- {name: 'Einberg', about: "<p><strong>A company with a focus on eco-friendly refurbishing.</strong> Einberg has established itself as a company working with only clean non-toxic materials, remodelling apartments for eco-conscious people.</p>", logo: 'clients3.png'}
- {name: 'Kavial', about: "<p><strong>Kavial is the biggest producer and distributor of ball bearings in Estonia.</strong> Their main focus are ball bearings, but they also distribute other car equipment.</p>", logo: 'clients1.png'}


